// components/Loader.vue
<script>
  export default {
    name: "Loader",

    mounted() {
      const loading = document.getElementById("loading");

      setTimeout(() => {
        loading.classList.add("animated", "fadeOut");

        setTimeout(() => loading.style.display = "none", 800);
      }, 1500);
    }
  }
</script>

<template>
  <span id="loading"><span id="spinner"></span></span>
</template>

<style lang="scss">
  #loading {
    height: 100vh;
    width: 100vw;

    position: fixed;
    top: 0; left: 0;
    
    background: var(--bg-color);

    z-index: 10;

    display: grid;
    place-content: center;
  }

  #spinner {
    height: 50px;
    width: 50px;

    animation: rotate 0.5s infinite linear;

    border: 2px solid var(--bg-color);
    border-bottom: 2px solid var(--text-color);
    border-radius: 50%;
  }

  @keyframes rotate {
    0% {
      transform: rotate(0deg);
    }

    100% {
      transform: rotate(360deg);
    }
  }
</style>

// src/lib/components/Loader.svelte
<script lang="ts">
    import {onMount} from "svelte";

    onMount((): void => {
        const loading = document.getElementById("loading");

        setTimeout((): void => {
            loading.classList.add("animate-fadeOut");

            setTimeout(() => loading.style.display = "none", 500);
        }, 1000);
    });
</script>

<span class="h-full w-full fixed top-0 left-0 z-10 grid place-content-center bg-black" id="loading">
    <span class="h-14 w-14 border-2 text-white bg-black animate-spin"></span>
</span>
